model:
  name: 'bert-base-uncased'
  num_classes: 2
  max_length: 128

training:
  batch_size: 32
  epochs: 5
  learning_rate: 1e-3

data:
  train_path: 'data/train.jsonl'
  val_path: 'data/val.jsonl'
  test_path: 'data/test.jsonl'
